Update xenium-flash.cpp
kooscode/xenium-programmer pull request #16
Opened 2022-07-22 12:03 UTC by catogtp

To mimic the same check in xenium-tools to verify the flash is ready for the next write, otherwise it will be ignored and could fail verify.

2022-07-22 13:08 UTC, dtomcat approved these changes

2022-08-08 06:11 UTC, kooscode requested changes
Please see code comment regarding infinite loop.

2022-08-08 06:11 UTC, kooscode commented on xenium-flash/src/xenium-flash.cpp
> +        while(flash.Read(0) != flash.Read(0));
This is an infinite while loop.  

please provide X amount of retries with error condition if it fails..

2022-11-08 04:37 UTC, kooscode commented
Pull request failed to address requested changed.. closing.

2022-11-08 04:37 UTC, closed without merging